export const ADD_CURRENCY_TO_FAVORITES = 'app/ADD_CURRENCY_TO_FAVORITES';

export const DELETE_CURRENCY_FROM_FAVORITES = 'app/DELETE_CURRENCY_FROM_FAVORITES';

export const FLUSH_FAVORITES = 'app/FLUSH_FAVORITES';