export const GET_NBP_CURRENCY_BEGIN = 'api/GET_NBP_CURRENCY_BEGIN';
export const GET_NBP_CURRENCY_SUCCESS = 'api/GET_NBP_CURRENCY_SUCCESS';
export const GET_NBP_CURRENCY_END = 'api/GET_NBP_CURRENCY_END';