export const GET_NBP_CURRENCIES_BEGIN = 'api/GET_NBP_CURRENCIES_BEGIN';
export const GET_NBP_CURRENCIES_SUCCESS = 'api/GET_NBP_CURRENCIES_SUCCESS';
export const GET_NBP_CURRENCIES_FAILURE = 'api/GET_NBP_CURRENCIES_FAILURE';